blank_issues_enabled: false
contact_links:
  - name: Discord Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: Reddit Community Support
    url: https://www.reddit.com/r/bronygamedev/
    about: Please ask and answer questions here.
  - name: Github Community Support
    url: https://github.com/bronygamedev/friendship-globe/discussions
    about: Please ask and answer questions here.
  - name: bronygamdev Security vulnerabilities
    url: https://form.jotform.com/232447338546058
    about: Please report security vulnerabilities here.
